### ISSUE TITLE
Return an auth token from Client::auth

### ISSUE THREAD

**Issue by mattarnoatibm** [krustlet/oci-distribution#104]
There are container registry API extensions that are not supported by the OCI distribution rust crate. So we can use the auth function from the OCI Distribution create to authenticate with a container registry in other crates the support the custom registry API extensions, we would want the `Client::auth` function to return an auth token.

**Comment by mattarnoatibm** [comment]
The PR to implement this is https://github.com/krustlet/oci-distribution/pull/105.

**Comment by flavio** [comment]
Closing, the PR has been merged
