### ISSUE TITLE
Git history messy

### ISSUE THREAD

**Issue by kflansburg** [krustlet/oci-distribution#18]
I just did a fresh clone of this repo and it took several minutes and over 40 MB. I'm not sure if this is a byproduct of extracting the new repo, but we should consider cleaning this up.

**Comment by bacongobbler** [comment]
GitHub will periodically run `git gc` on a repository, but I don't see a way to control this on the server side. How would you suggest we fix this?

**Comment by kflansburg** [comment]
> GitHub will periodically run `git gc` on a repository, but I don't see a way to control this on the server side. How would you suggest we fix this?

I think that the issue is that some large (or many small) files were added at some point and then removed. They are still part of history, so would probably not be caught by `git gc`. 


Running the suggestion from [here](https://stackoverflow.com/questions/10622179/how-to-find-identify-large-commits-in-git-history), I see the following files which seem like they should not have been included in the history when it was extracted from `krustlet`. When we created the `krator` repository, I "rewrote history" to remove files like this permanently. This will have to be done with a force push to `main` unfortunately. 



```
04abd0c6cc06  462KiB crates/wascc-provider/lib/libwascc_logging.dylib
6e68ea6d8593  1.4MiB crates/wascc-provider/lib/libwascc_logging.dylib
86ffb3faaa34  1.5MiB crates/wascc-provider/testdata/libecho_provider.dylib
2f339d96b836  1.5MiB crates/wasi-provider/testdata/hello-world.wasm
fa49ed904e87  1.8MiB crates/wascc-provider/testdata/echo_actor_signed.wasm
6d1bf3d51678  1.8MiB crates/wascc-provider/testdata/greet_actor_signed.wasm
c3c456099807  2.1MiB crates/wascc-provider/testdata/echo_actor_s.wasm
7710900dea1b  2.1MiB crates/wascc-provider/testdata/echo.wasm
93bc3563af08  2.7MiB crates/wascc-provider/lib/libwascc_logging.so
6b86f3dca0a4  4.1MiB crates/wascc-provider/lib/libwascc_httpsrv.dylib
dc1dd132388d  4.2MiB crates/wascc-provider/lib/libwascc_httpsrv.dylib
91e1f5ad7cd5  4.2MiB crates/wascc-provider/lib/libwascc_httpsrv.dylib
423c3ca96c93  4.7MiB lib/greet_actor_signed.wasm
8e53aa2ecd4b  4.7MiB lib/greet_actor.wasm
e495bca67397  5.6MiB crates/wascc-provider/testdata/libecho_provider.dylib
6bf0c72f50ba  7.2MiB crates/wascc-provider/lib/libwascc_httpsrv.so
a93c9301f54f  7.3MiB crates/wascc-provider/lib/libwascc_httpsrv.so
7cd6a69acd5b  7.3MiB crates/wascc-provider/lib/libwascc_httpsrv.so
1f0f13174658  8.4MiB crates/wascc-provider/testdata/testlogging_signed.wasm
ccfe35da91f2  8.4MiB crates/wascc-provider/lib/libwascc_logging.so
255c84a5778a  8.4MiB crates/wascc-provider/lib/libwascc_logging.so
55b9af23b23c  8.4MiB crates/wascc-provider/lib/libwascc_logging.so
dfe14f96b76c  8.4MiB crates/wascc-provider/lib/libwascc_logging.so
8a372687e933  8.7MiB crates/wascc-provider/testdata/testlogging_signed.wasm
90bb6be91310   17MiB crates/wascc-provider/testdata/libecho_provider.so
cd429401f78f   17MiB crates/wascc-provider/testdata/libecho_provider.so
5e02bdfe9e84   18MiB crates/wascc-provider/lib/libwascc_logging.so
0a20a55369a0   18MiB lib/libwascc_httpsrv.dylib
```

**Comment by flavio** [comment]
Ouch, this is a bit unfortunate (the need to run a force push). I think we can coordinate around that, right now we have just one open PR.

I would be in favor of doing this operation

**Comment by thomastaylor312** [comment]
Circling back on this, I think it is definitely work doing, we just need to make sure we communicate well. Probably better to do this before uptake on this repo gets too high (as it seems to be increasing)

**Comment by aochagavia** [comment]
Any chance on getting this done in the short term? This crate is currently the most popular Rust OCI client, so it seems worthwhile to do it

**Comment by thomastaylor312** [comment]
@flavio We should probably run this cleanup now since the crate is growing in popularity. Thoughts on doing this along with a huge note at the top of the README to explain that we had to clean up the history. Just need to work through @aochagavia's PR first

**Comment by flavio** [comment]
@thomastaylor312 I'm fine doing that once https://github.com/krustlet/oci-distribution/pull/63 is merged.

**Comment by aochagavia** [comment]
As the author of #63, I don't mind if you rewrite the git history before it is merged, because I can easily rebase my changes on top of the result (it is just one commit). Don't let my PR hold you back 😉 (I'll only have time to work on it next week).

**Comment by thomastaylor312** [comment]
This is now fixed! Please make sure to reclone the repo to pick up the modified history
