### ISSUE TITLE
Failed on CI test for `test_image_roundtrip_basic_auth`

### ISSUE THREAD

**Issue by Xynnn007** [krustlet/oci-distribution#49]
Related error message is 
```
failures:

---- client::test::test_image_roundtrip_basic_auth stdout ----
thread 'client::test::test_image_roundtrip_basic_auth' panicked at 'authenticated: AuthenticationFailure("{\"errors\":[{\"code\":\"UNAUTHORIZED\",\"message\":\"aad access token with sp failed client id must be guid\"}]}")', src/client.rs:2203:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Seems related to ACR authentication. I tried to debug and this error occured when POST to `"https://webassembly.azurecr.io/oauth2/token"` with HTTP Authenticated Header `Basic <base64-encoded "testuser">:<base64-encoded "testpassword">`.

I'm not sure whether it is caused by ACR? Any suggestions, please @flavio

**Comment by flavio** [comment]
I fixed this broken test with https://github.com/krustlet/oci-distribution/pull/52
