### ISSUE TITLE
Move `src/www_authenticate` into a sub-crate

### ISSUE THREAD

**Issue by flavio** [krustlet/oci-distribution#7]
The directory `src/www_authenticate` contains a copy of the [www-authenticate](https://crates.io/crates/www-authenticate) crate. I realize this is an approach that was taken when `oci-distribution` was a sub-crate of `krustlet`.

I propose to turn this module into a sub-crate, so that `cargo build|check|...` stops producing tons of warning messages, one per public method of the `www-authenticate` module that `oci-distribution` doesn't use.

A quick example:

```console
warning: associated function is never used: `get_mut`
   --> src/www_authenticate/mod.rs:253:16
    |
253 |         pub fn get_mut(&mut self, k: &str) -> Option<&mut String> {
    |                ^^^^^^^

warning: associated function is never used: `insert_quoting`
   --> src/www_authenticate/mod.rs:265:16
    |
265 |         pub fn insert_quoting(&mut self, k: String, v: String) -> Option<String> {
    |                ^^^^^^^^^^^^^^

warning: `oci-distribution` (lib) generated 14 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 1.03s
```

In theory, moving everything into a sub-crate should allow us to get rid of these warnings

**Comment by flavio** [comment]
@kflansburg, @thomastaylor312, @bacongobbler: what do you think about this proposal? If you are fine with that I can give it a shot and see if I can make the warnings disappear

**Comment by thomastaylor312** [comment]
I am definitely in favor of making this a subcrate

**Comment by flavio** [comment]
According to our README, we have this code copied into the oci-distribution repository because:

> This code was copied from https://github.com/KeenS/www-authenticate, which is unlicensed.

I double checked, and now the crate has a MIT license. The license is stated explicitly inside of its [Cargo.toml](https://github.com/KeenS/www-authenticate/blob/612fbd949d137f2bd7b41b3a072ab3932a813bd6/Cargo.toml#L5) file, but there's no `LICENSE` file inside of the git repository.

Should I go ahead with this issue or should we consume the crate from `crates.io`?

I just want to understand the whole issue before doing this change :pray:
